### ISSUE TITLE
Remove/update cypress dependency

### ISSUE THREAD

**Issue by pburkindine** [andrewmcoupe/cy-view#5]
Hello,

We love this package, thanks!  However, its dependencies are behind the current version, which has the effect in our CI pipelines of causing npm to install both the current 7.x version and the 3.6.0 version currently listed in the package.json of this project.  This slows down our pipelines substantially.

Would it be possible to change the dependency to be more future-proof?

Thanks!

**Comment by andrewmcoupe** [comment]
Hey @pburkindine and thanks for raising the issue 😄 

I'll remove this from the deps in the next couple of days 👍

**Comment by pburkindine** [comment]
Awesome, thanks mate

**Comment by andrewmcoupe** [comment]
Removed from dependencies 👍
